name: Triggering Events
on: 
  push:
    branches:
        - "testing workflows"
  pull_request:
    branches:
        - "test-branch"
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
jobs:
    echo-event:
            runs-on: ubuntu-24.04
            steps:
                - run: echo "This workflow is triggered by push, pull request, schedule and workflow dispatch events...."

